@echo off
REM ============================================================
REM  Task runner wrapper - generated by install_task.ps1
REM  Initializes environment + runs wechat_daily.py + logs output
REM ============================================================

REM Switch to project directory
cd /d "%~dp0"

REM Add all possible Python paths to PATH (compatible with Microsoft Store version)
set "PATH=%LOCALAPPDATA%\Microsoft\WindowsApps;%LOCALAPPDATA%\Programs\Python\Python314;%LOCALAPPDATA%\Programs\Python\Python313;%LOCALAPPDATA%\Programs\Python\Python312;C:\Python314;C:\Python313;C:\Python312;C:\Program Files\Python314;C:\Program Files\Python313;C:\Program Files\Python312;%PATH%"

REM Add Python user site-packages to PYTHONPATH (ensure pywinauto etc. can be found)
set "PYTHONPATH=%APPDATA%\Python\Python314\site-packages;%APPDATA%\Python\Python313\site-packages;%APPDATA%\Python\Python312\site-packages;%APPDATA%\Python\Python311\site-packages;"

REM Timestamp
echo. >> logs\task_run.log
echo ============================================================ >> logs\task_run.log
echo [%date% %time%] Task started >> logs\task_run.log
echo ============================================================ >> logs\task_run.log

REM Run python script (use 'python' not absolute path, PATH is set above)
python wechat_daily.py >> logs\task_run.log 2>&1

REM Record exit code
echo. >> logs\task_run.log
echo [%date% %time%] Task ended, exit code: %ERRORLEVEL% >> logs\task_run.log
echo ============================================================ >> logs\task_run.log

REM Pass through exit code
exit /b %ERRORLEVEL%
